module.exports = [
  { id: 'manifest.mv3', label: 'Manifest V3 shell' },
  { id: 'manifest.permissions', label: 'Extension permissions and web resources' },
  { id: 'entrypoint.context_menu', label: 'Right-click summary entrypoint' },
  { id: 'entrypoint.shortcut', label: 'Alt+S shortcut entrypoint' },
  { id: 'entrypoint.status', label: 'Entrypoint status and shortcut checks' },
  { id: 'content.extraction', label: 'Page content extraction' },
  { id: 'content.sidebar_injection', label: 'Sidebar iframe injection and viewport sync' },
  { id: 'article.snapshot', label: 'Article snapshot normalization' },
  { id: 'article.chunking', label: 'Long article chunking' },
  { id: 'page.strategy', label: 'Page type strategy selection' },
  { id: 'prompt.primary', label: 'Primary summary prompt builders' },
  { id: 'prompt.secondary', label: 'Secondary generation prompt builders' },
  { id: 'generation.primary', label: 'Primary summary generation flow' },
  { id: 'generation.long_chunking', label: 'Long article staged generation flow' },
  { id: 'generation.secondary', label: 'Secondary generation flow' },
  { id: 'settings.presets', label: 'Provider preset settings' },
  { id: 'settings.autosave', label: 'Popup autosave contract' },
  { id: 'settings.connection_test', label: 'Connection test action' },
  { id: 'settings.theme', label: 'Theme preference sync' },
  { id: 'provider.openai', label: 'OpenAI-compatible adapter' },
  { id: 'provider.anthropic', label: 'Anthropic-compatible adapter' },
  { id: 'provider.registry', label: 'Adapter registry' },
  { id: 'transport.streaming', label: 'SSE streaming transport' },
  { id: 'transport.non_stream', label: 'Non-stream transport parsing' },
  { id: 'transport.errors', label: 'Transport error normalization' },
  { id: 'run.cancellation', label: 'Generation cancellation' },
  { id: 'run.diagnostics', label: 'Runtime diagnostics summaries' },
  { id: 'history.storage', label: 'IndexedDB summary records' },
  { id: 'history.search', label: 'History search' },
  { id: 'history.site_filters', label: 'History site grouping and filtering' },
  { id: 'history.favorite_delete', label: 'Favorites and deletion' },
  { id: 'history.reuse_current_page', label: 'Reusable current-page history' },
  { id: 'privacy.policy', label: 'Privacy/no-trace policy' },
  { id: 'reader.session', label: 'Reader session creation and lookup' },
  { id: 'reader.page', label: 'Standalone reader page contract' },
  { id: 'export.markdown', label: 'Markdown export and copy' },
  { id: 'export.share_card', label: 'Share card image export' },
  { id: 'ui.sidebar_contract', label: 'Sidebar DOM contract' },
  { id: 'ui.popup_contract', label: 'Popup DOM contract' },
  { id: 'ui.reader_contract', label: 'Reader DOM contract' },
  { id: 'quality.syntax', label: 'First-party JavaScript syntax' },
  { id: 'quality.performance_baseline', label: 'Large history performance baselines' },
  { id: 'quality.docs_upgrade_design', label: 'Upgrade design documentation' }
];
